PortAudio/portaudio

.github/workflows/c-cpp.yml

Try .configure && make on Ubuntu Linux

add Continuous Integration using an Action

---

doc/src/mainpage.dox
doc/src/tutorial/compile_windows_mingw.dox
doc/src/tutorial/tutorial_start.dox

docs: change Assembla links to GitHub

---

.github/workflows/c-cpp.yml

Add GitHub actions for building with CMake and MSVC

---

include/pa_win_wasapi.h
src/hostapi/wasapi/pa_win_wasapi.c

Support multiple devices in the device list on Windows UWP/WiRT platform:
- All UWP/WinRT functions are now prefixed as PaWasapiWinrt_ to be clearly visible, therefore PaWasapi_SetDefaultInterfaceId() was renamed to PaWasapiWinrt_SetDefaultDeviceId(). 
- Expanded Important notes regarding UWP/WinRT platform and how to make the fully-functional device list with the corresponding pseudo-code example for easier understanding of the functionality.
The device list management API is trivial:
```c
std::vector<const UINT16 *> ids, names;
std::vector<PaWasapiDeviceRole> role;
ids.resize(count);
names.resize(count);
role.resize(count);
for (UINT32 i = 0; i < count; ++i)
{
ids[i]   = (const UINT16 *)device_ids[i].c_str();
names[i] = (const UINT16 *)device_names[i].c_str();
role[i]  = …
```

wasapi: Support multiple devices in the device list on Windows UWP/WiRT platform.

---

src/hostapi/coreaudio/pa_mac_core.c

These APIs are deprecated in 10.8+ and are disabled on 11.0(10.16)+ https://developer.apple.com/documentation/coreservices/carbon_core/component_manager?language=objc
Console output trying to use existing portaudio in Xcode 12.2 (beta)
> "This application, or a library it uses, is using the deprecated Component Manager for hosting Audio Components. This is not supported when rebuilding against the 10.16 or later SDK. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h."

Replace usage of deprecated component manager APIs on 10.6+

---

src/hostapi/wasapi/pa_win_wasapi.c

Fixed underruns in the Exclusive mode on UWP platform (or when timeBeginPeriod does not allow to set 1 ms granularity) by assuming that system timer granularity on UWP equals to 10 msec.
Also, make sure time to sleep provided by GetNextSleepTime is aligned to the granularity of the system timer to avoid underruns with a short sleeps, for example when capturing on UWP platform or when system timer granularity is more than 1.

wasapi: Fixed underruns in the Exclusive mode on UWP platform.

---

build/msvc/portaudio.def

PaWasapi_SetDefaultInterfaceId being renamed in #340 caused the project to error out when building with Visual Studio

Update def files for #340

---

src/hostapi/dsound/pa_win_ds.c
src/hostapi/dsound/pa_win_ds_dynlink.c
src/hostapi/dsound/pa_win_ds_dynlink.h

Clean up whitespace in src\hostapi\dsound in preparation for .editorconfig,

---

qa/loopback/src/audio_analyzer.c
qa/loopback/src/audio_analyzer.h
qa/loopback/src/biquad_filter.c
qa/loopback/src/biquad_filter.h
qa/loopback/src/paqa.c
qa/loopback/src/paqa_tools.c
qa/loopback/src/paqa_tools.h
qa/loopback/src/qa_tools.h
qa/loopback/src/test_audio_analyzer.c
qa/loopback/src/test_audio_analyzer.h
qa/loopback/src/write_wav.c
qa/loopback/src/write_wav.h
qa/paqa_devs.c
qa/paqa_errs.c
qa/paqa_latency.c

Clean up whitespace in qa/ in preparation for .editorconfig.

---

test/patest1.c

Got changed from fprintf accidentally.
Fixes #466

Fix patest1 printf

---

src/hostapi/wdmks/pa_win_wdmks.c

Indent by 4 spaces. Strip trailing whitespace.

Clean up whitespace in src/hostapi/wdmks in preparation for .editorconfig.

---

src/hostapi/wasapi/pa_win_wasapi.c

Indent by 4 spaces. Strip trailing whitespace.

Clean up whitespace in src/hostapi/wasapi in preparation for .editorconfig.

---

src/hostapi/asio/pa_asio.cpp

Cleanup newlines in asio

---

src/common/pa_allocation.c
src/common/pa_front.c

Cleanup newlines in src/common

---

src/os/win/pa_win_hostapis.c

Cleanup newlines in src/os/win

---

src/hostapi/skeleton/pa_hostapi_skeleton.c

Cleanup endlines in skeleton

---

src/hostapi/coreaudio/pa_mac_core.c
src/hostapi/coreaudio/pa_mac_core_blocking.c
src/hostapi/coreaudio/pa_mac_core_blocking.h
src/hostapi/coreaudio/pa_mac_core_internal.h
src/hostapi/coreaudio/pa_mac_core_utilities.c
src/hostapi/coreaudio/pa_mac_core_utilities.h

Clean up whitespace in src/hostapi/coreaudio in preparation for .editorconfig.

---

src/hostapi/jack/pa_jack.c

Improves previously merged PR #405 master commit eec7bb7 by performing string conversion directly in to the target buffer, thus avoiding one allocation and one strncpy per client/device name.
NOTE: I have not tested this change.

Improve JACK regex pattern escape code (see ticket #534). 

---

test/patest_sine_time.c

On ALSA the StreamTime was not advancing so the while()
loop never exited. Now it will time out if it plays for much
longer than expected without the stream time changing.

test: time out in patest_sine_time.c

---

src/hostapi/wasapi/pa_win_wasapi.c

Check for the supported Windows version explicitly in PaWasapi_Initialize() and avoid relying on existence on avrt.dll for detecting the compatible platform. 
User could provide avrt.dll stub that will break initialization of the library if OS version does not support WASAPI backend.
Fixes #617 issue.

wasapi: Improved reliability of the supported platform check.

---

.github/workflows/cmake.yml
src/hostapi/jack/pa_jack.c
src/os/win/pa_win_hostapis.c
vcpkg.json

fix JACK host API build for MSVC and MinGW

---

src/hostapi/alsa/pa_linux_alsa.c

If alsalib is installed this causes a compilation failure :x

alsa: Fix building on BSD

---

.github/workflows/cmake.yml

CI: use apt-get update to fix libasound2-dev

---

test/patest_callbackstop.c

Query Pa_IsStreamActive() and Pa_IsStreamStopped()
and verify correct response.

test: check active and stopped states

---

CMakeLists.txt

Fix CMAKE_INSTALL_INCLUDEDIR not being defined

---

src/hostapi/coreaudio/pa_mac_core_utilities.c

Mac: change some internal errors to host errors.

---

.github/workflows/cmake.yml
src/hostapi/jack/pa_jack.c

Addresses an issue discussed in the comment stream of #695 (but not the issue itself)

JACK: fix assertion checking client name length

---

include/pa_win_wasapi.h

Some cleanup of comments regarding Event and Poll-driven methods of WASAPI back-end as part of discussion in #700.
Closes #700

wasapi: Adjusted comments for paWinWasapiPolling and Event/Poll-driven methods.

---

test/patest1.c

Avoid error when requesting stereo input.
Also removed confusing stop after 20 seconds
that conflicted with stopping by key press.
For #595

patest1: use mono input

---

examples/pa_fuzz.c
examples/paex_record.c

Fix stereo input in tests

---

include/pa_win_wasapi.h
src/hostapi/wasapi/pa_win_wasapi.c

: tabs -> 4 spaces, delete trailing whitespace

pa_win_wasapi.c, pa_win_wasapi.h fix whitespace

---

.github/workflows/cmake.yml

Install pkg-config in the macOS CMake CI

---

include/pa_win_wasapi.h

Addresses @RossBencina's https://github.com/PortAudio/portaudio/pull/778#discussion_r1199479119

wasapi: Extended documentation comments for paWinWasapiPassthrough.

---

CMakeLists.txt
qa/loopback/src/paqa.c
qa/paqa_devs.c
qa/paqa_latency.c
src/hostapi/jack/pa_jack.c
test/patest_latency.c

Fix MSVC warning C4018 signed/unsigned mismatch

---

src/hostapi/jack/pa_jack.c

JACK connection managers save/load the connection graph so users don't need to create connections manually every time. This depends on stable port names but PortAudio currently generates incrementing port names throughout the lifetime of a running process.
Reset the port name counters when all streams are closed so that the same port names are generated when the streams are opened again.
This is not a perfect solution because applications that open streams in different orders each time or never close all open streams before restarting audio processing will not reset the port counters. However, typical applications should work with this simple approach and it's an improvement over current behavior.
Tested with Audacity 3.3.3 on Fedora 39.

JACK: try to use stable port names

---

src/hostapi/wmme/pa_win_wmme.c

Replace infinite looping with bounded looping in ReadStream and WriteStream if the stream stalls for some reason. Causes ReadStream and WriteStream to return `paTimedOut` after a long timeout (currently set to 3 times the total buffer duration).
Note that ideally we'd detect that the wmme stream has failed rather than depending on timeouts, but there doesn't seem to be an API for that.
Note that stalling is possibly driver-dependent but has been observed after system sleep/hibernation in #883.
Proposed fix for #883

wmme: fix ReadStream and WriteStream infinite timeout loops

---

include/portaudio.h

Update Pa_AbortStream docs to better indicate intent. Fixes #728.

---

examples/paex_record_file.c

This casting seems to be necessary in the example. Do I miss something?

remove unnecessary casting in the example

---

qa/paqa_devs.c

Fix prototype warning in qa/paqa_devs.c

---

configure
configure.in

add src/os/win/pa_win_version.c to windows ./configure based builds
