src/hostapi/wasapi/pa_win_wasapi.c

Fixing #303 by reducing the sleep delays on playback in polled thread mainloop. This reverts the sleep delays back to the same values as used in the stable versions of PA.

Implement fix for glitching WASAPI playback

---

README.md

I have started to use portaudio for my project.
I found an link to a tutorial page in README.md but a link was broken.
This pull request fixes it.

Fix an url of Tutorial start page in README.md.

---

src/hostapi/wasapi/pa_win_wasapi.c

To combat underruns there were several changes implemented:
1. Implemented workaround for system timer coarse granularity causing underruns by using timeBeginPeriod/timeEndPeriod APIs inside the Event and Poll thread handlers. Coarse system timer breaks precision of waiting for a next time slot causing underruns as a result.
2. Updated next sleep time of the Poll rendering loop dynamically depending on time taken for processing/rendering of audio data into the available host buffer to avoid underruns and fit processing time into periodic polling time slots. It will minimize possibility of the underruns if user buffer is 1/2 of the host buffer and user code takes less than 1/2 of the host buffer duration.

wasapi: Improvement to lower possible cases of underruns due to coarse system timer and time-hungry user-side processing..

---

src/hostapi/wasapi/pa_win_wasapi.c

Fix paInvalidSampleRate (and any other) error code is replaced with paInvalidDevice if audio client failed to be created due to some reason. 
Not critical but does not allow to report reason of failure to the user correctly.
Closes #314

wasapi: Fix paInvalidSampleRate (and any other) error code is replaced with paInvalidDevice.

---

src/hostapi/wdmks/pa_win_wdmks.c

Note that PaUtil_AllocateMemory currently calls GlobalAlloc without the GMEM_ZEROINIT flag, so there was no guarantee that filter->pins[pinId] was zero.

wdmks: ensure that pins that failed creation by PinNew() are zeroed.

---

src/hostapi/alsa/pa_linux_alsa.c

Option to ignore all ALSA plugin devices by using PA_ALSA_IGNORE_ALL_PLUGINS environment variable. 
Fixed logic of guarding assertion in BuildDeviceList() when only one PCM device is available (may occur if PA_ALSA_IGNORE_ALL_PLUGINS is defined).
Ignoring ALSA plugin devices is useful when using using PortAudio with ALSA interface in embedded systems like [Yocto Linux](http://www.yoctoproject.org). Some plugins are causing segfaults and practically may not be needed at all for the developer. By defining PA_ALSA_IGNORE_ALL_PLUGINS developer is able to switch off Alsa Plugin devices, only PCM devices will exist in this case (internal sound card, USB DAC, ...).

alsa: Option to ignore all ALSA plugin devices.

---

src/hostapi/coreaudio/pa_mac_core_utilities.c
src/hostapi/coreaudio/pa_mac_core_utilities.h

Insert "void" in the argument list to turn initializeXRunListenerList and destroyXRunListenerList declarations into valid prototypes. Also update the function definitions to match. Thanks to Paul Boersma.

pa_mac_core_utilities: add void to empty function argument list

---

src/os/win/pa_win_waveformat.c

Fixed breaking strict-aliasing rules (if compiled with GCC with -fstrict-aliasing) in PaWin_InitializeWaveFormatExtensible().
Cosmetic changes: replaced tabs with 4 spaces and trimmed trailing spaces.
GCC's warning without a fix looks like this:
```c
pa_win_waveformat.c: In function 'PaWin_InitializeWaveFormatExtensible':
pa_win_waveformat.c:101:2: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
*((WORD*)&waveFormat->fields[PAWIN_INDEXOF_WVALIDBITSPERSAMPLE]) =
^
pa_win_waveformat.c:104:2: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
*((DWORD*)&waveFormat->fields[PAWIN_INDEXOF_DWCHANNELMASK]) = channelMask;
^
pa_win_waveformat.c:108:5: warning: dereferencing type-punned pointer will break …
```

Fix breaking strict-aliasing rules (if compiled with GCC with -fstrict-aliasing in PaWin_InitializeWaveFormatExtensible()

---

src/hostapi/wdmks/pa_win_wdmks.c

Fix GUID define when compiling with clang-cl
```
In file included from /vcpkg/buildtrees/portaudio/src/ebd3ebfacc-58e92047a8.clean/src/hostapi/wdmks/pa_win_wdmks.c:187:
/clang_windows_sdk/winsdk/Include/10.0.18362.0/shared/mmreg.h(2474,1): error: too many arguments provided to function-like macro invocation
DEFINE_GUIDSTRUCT("00000001-0000-0010-8000-00aa00389b71", KSDATAFORMAT_SUBTYPE_PCM);
^
/clang_windows_sdk/winsdk/Include/10.0.18362.0/shared/mmreg.h(2462,33): note: expanded from macro 'DEFINE_GUIDSTRUCT'
#define DEFINE_GUIDSTRUCT(g, n) DEFINE_GUIDEX(n)
^
/vcpkg/buildtrees/portaudio/src/ebd3ebfacc-58e92047a8.clean/src/hostapi/wdmks/pa_win_wdmks.c(168,47): note: expanded from macro 'DEFINE_GUIDEX'
#define DEFINE_GUIDEX(n) DEFINE_GUID_THUNK(n, STATIC_##n)
^
<scratch space>(205,1): note: …
```

Fix GUID defines in pa_win_wdmks.c when compiling with clang-cl

---

src/common/pa_debugprint.c

This is a simple PR that fixes the following warning on Windows:
pa_debugprint.c(1,1): warning C4828: The file contains a character starting at offset 0xa95 that is illegal in the current source character set (codepage 65001)

fix non latin1 character in pa_debugprint.c

---

src/os/win/pa_win_coinitialize.c
src/os/win/pa_win_coinitialize.h

This change eliminates compiler warning on MSVC
`pa_win_coinitialize.c(136,53): warning C4389: '!=': signed/unsigned mismatch`

Change PaWinUtilComInitializationResult::initializingThreadId to DWORD to match the native type of WIN32 thread id

---

src/hostapi/alsa/pa_linux_alsa.c

This fixes #268 
This patch was original proposed by Chameleon here: 
https://portaudio.music.columbia.narkive.com/3V9hsUak/pa-linux-alsa-c-3636-assertion-failed-with-hack-fix

Don't crash if alsa_snd_pcm_poll_descriptors fails

---

src/hostapi/wmme/pa_win_wmme.c

WMME Fix compiler warnings: 'type cast': conversion from 'int' to 'HWAVEIN' of greater size.

---

src/hostapi/wasapi/pa_win_wasapi.c

Always define PaWasapi_UpdateDeviceList(), even when it is a no-op, because it is mentioned in the .def file.

Fix issue #321 broken MSVC build. 

---

qa/paqa_devs.c

Use sine wave instead of sawtooth because it is
easier to hear glitches.
Add some options:
-a - Test ALL devices, otherwise just the default devices.
-i - Test INPUT only.
-o - Test OUTPUT only.

paqa_devs: test default device

---

src/hostapi/alsa/pa_linux_alsa.c

Given
unsigned int reqRate, setRate, deviation;
then 
setRate - reqRate
is also an unsigned int - the code works "by chance" as `abs` casts that to an int which overflows and is technically undefined behaviour, for instance for setRate = 44100 and reqRate = 48000.
Thus cast them to int when computing the absolute value to ensure no UB.

Fix a GCC warning due to unsigned substraction

---

.github/workflows/MSBuild.yml

Adds `.github/workflows/MSBuild.yml` file that performs a GitHub action to build PA using the msvc project file in `build/msvc`
The action performs the following automated steps:
- Updates the `.vcproj` file to the new format `.vcxproj`.
- Removes ASIO files from the build, including removing ASIO-specific symbols from the .def file (we can't ship ASIO SDK files)
- Enables the `PA_USE_DS=1` DirectSound flag
- Performs Release builds using both Win32 (32-bit) and x64 (64-bit) options
Fixes #368.

Add new GitHub action to build PortAudio using the MSVC project file

---

src/hostapi/wdmks/pa_win_wdmks.c

Fixes issue with Focusrite Scarlett 2i4 (1st Gen). Thanks to Stefan Hajnoczi. Fixes #310

wdmks: Reset packet->Header.OptionsFlags = 0 for each packet.

---

src/hostapi/wdmks/pa_win_wdmks.c

Alternative solution for PR #377.

wdmks: Fix 'uninitialized variable used' warnings.

---

src/hostapi/dsound/pa_win_ds.c
src/hostapi/wmme/pa_win_wmme.c

Fixes MME and DSound ANSI characters under MBCS builds. Despite what MS docs say, MME actually does provide non-TCHAR methods (noticed it when Visual Studio IntelliSense suggested them).
While fixing the device names, I've noticed that MME error macros also used ANSI, so i fixed them aswell.
Fixes #224.
Tested on my machine (in my test app which i'm using for integrating PortAudio in our Unity game, thus we use a custom ordering and include the API and Exclusive in the name):
```
VoiceMeeter Output (VB-Audio VoiceMeeter VAIO) (Windows WASAPI)
VoiceMeeter Output (VB-Audio VoiceMeeter VAIO) (Windows WASAPI) - Exclusive
Trust Starzz (Realtek High Definition Audio) (Windows WASAPI)
Trust Starzz (Realtek High Definition Audio) (Windows WASAPI) - Exclusive
Podstawowy sterownik przechwytywania …
```

Fix to use UTF-8 text instead of ANSI in MME and DSound

---

src/hostapi/wasapi/pa_win_wasapi.c

Report thread running so Pa_StartStream can return prior to PaStreamCallback.
StartStream() calls WaitForSingleObject(stream->hThreadStart, 60*1000)
but it will not be able to return until X number of PaStreamCallback
have been performed by ProcessOutputBuffer().
The above behaviour will cause a deadlock if the user supplied
PaStreamCallback tries to access a shared lock currently held by the
function calling Pa_StartStream().
Also it's a bit weird that you start receiving PaStreamCallbacks
before Pa_StartStream() is able to complete.

WASAPI: Report thread running so Pa_StartStream can return

---

src/hostapi/wasapi/pa_win_wasapi.c

In file pa_win_wasapi.c we compare signed SystemTimer::granularity with unsigned TIMECAPS::wPeriodMin.
This PR resolves the issue.

wasapi: Fix signed/unsigned mismatch warning.

---

cmake_support/template_portaudio.def

This omission made it impossible to use `PaWasapi_GetDeviceMixFormat()` from a PortAudio DLL built using CMake.

Add missing PaWasapi_GetDeviceMixFormat cmake DLL export

---

src/hostapi/oss/pa_unix_oss.c

On FreeBSD /dev/dsp is the default device but may not be /dev/dsp0.
PortAudio in the FreeBSD ports collection initially had a patch to
replace the default device with /dev/dsp (for example, with three
devices and /dev/dsp1 as the default we'd have /dev/dsp0, /dev/dsp,
/dev/dsp2).  This caused some trouble (the first device is no longer
default) and was later replaced with this change, leaving /dev/dsp
as the first entry, and just adding each /dev/dsp%d that exists.
FreeBSD bugs 208968 and 236118.

OSS: include both /dev/dsp and /dev/dsp0

---

src/hostapi/oss/pa_unix_oss.c

Previously GetAvailableFormats returned paSampleFormatNotSupported if
AFMT_S16_NE was not supported, regardless of the supported state of any
other formats.  Instead, return paSampleFormatNotSupported if no
supported formats are found.

OSS: correct test for unsupported formats

---

src/hostapi/coreaudio/pa_mac_core.c
src/hostapi/coreaudio/pa_mac_core_utilities.c
src/hostapi/coreaudio/pa_mac_core_utilities.h

This pull request addresses item #218 by using the new CoreAudio APIs while keeping compatibility with
applications that need to use the old APIs!
This is done with the following check
#if (MAC_OS_X_VERSION_MIN_REQUIRED >= MAC_OS_X_VERSION_10_5)
#define PA_NEW_HAL 1
#else
#define PA_NEW_HAL 0
#endif
which checks if the application targets Mac OSX >= 10.5, so applications targeting Mac OS X 10.4 will use the old API.
I tried to make the changes as minimal as possible by introducing wrapper functions and #ifdefs
for two reasons:
a) easier review
b) compatibility with old API

CoreAudio add support for new HAL API for applications that target Mac OS X >= 10.5

---

include/pa_asio.h
include/pa_jack.h
include/pa_linux_alsa.h
include/pa_mac_core.h
include/pa_win_ds.h
include/pa_win_wasapi.h
include/pa_win_waveformat.h
include/pa_win_wdmks.h
include/pa_win_wmme.h
include/portaudio.h

Clean up whitespace in include/ in preparation for .editorconfig. 

---

src/hostapi/asihpi/pa_linux_asihpi.c
src/hostapi/jack/pa_jack.c
src/hostapi/oss/pa_unix_oss.c
src/hostapi/oss/recplay.c
src/hostapi/skeleton/pa_hostapi_skeleton.c

Clean up whitespace in src/hostapi/{asihpi, jack, oss, skeleton} in preparation for .editorconfig.

---

.gitignore

When using CMake, this file is written by Visual Studio to hold custom CMake parameters.

Ignore the Visual Studio CMake settings file

---

src/hostapi/asio/pa_asio.cpp

Clean up whitespace in pa_asio.cpp in preparation for .editorconfig.

---

src/hostapi/wmme/pa_win_wmme.c

Clean up whitespace in pa_win_wmme.c in preparation for .editorconfig

---

src/common/pa_allocation.c
src/common/pa_allocation.h
src/common/pa_converters.c
src/common/pa_converters.h
src/common/pa_cpuload.c
src/common/pa_cpuload.h
src/common/pa_debugprint.c
src/common/pa_debugprint.h
src/common/pa_dither.c
src/common/pa_dither.h
src/common/pa_endianness.h
src/common/pa_front.c
src/common/pa_hostapi.h
src/common/pa_memorybarrier.h
src/common/pa_process.c
src/common/pa_process.h
src/common/pa_ringbuffer.c
src/common/pa_ringbuffer.h
src/common/pa_stream.c
src/common/pa_stream.h
src/common/pa_trace.c
src/common/pa_trace.h
src/common/pa_types.h
src/common/pa_util.h

Convert tabs to 4 spaces. Indent by 4 spaces. Strip trailing whitespace.

Clean up whitespace in src/common in preparation for .editorconfig.

---

src/os/win/pa_win_coinitialize.c
src/os/win/pa_win_coinitialize.h
src/os/win/pa_win_hostapis.c
src/os/win/pa_win_util.c
src/os/win/pa_win_waveformat.c
src/os/win/pa_win_wdmks_utils.c
src/os/win/pa_win_wdmks_utils.h
src/os/win/pa_x86_plain_converters.c
src/os/win/pa_x86_plain_converters.h

Clean up whitespace in src/os/win in preparation for .editorconfig.

---

src/os/unix/pa_unix_hostapis.c
src/os/unix/pa_unix_util.c
src/os/unix/pa_unix_util.h

Clean up whitespace in src/os/unix in preparation for .editorconfig.

---

qa/loopback/src/audio_analyzer.c

Same as #454, in this case only a single EOL was doubled

Whitespace cleanup in qa

---

examples/paex_read_write_wire.c
examples/paex_record.c
examples/paex_record_file.c
examples/paex_wmme_ac3.c
examples/paex_wmme_surround.c

Same as #454, only a few doubled EOLs here.

Whitespace cleanup in examples

---

test/patest_dsound_find_best_latency_params.c
test/patest_dsound_low_level_latency_params.c
test/patest_dsound_surround.c
test/patest_mono.c
test/patest_read_record.c
test/patest_wmme_find_best_latency_params.c
test/patest_wmme_low_level_latency_params.c

Same as #454, in this case there were only doubled EOLs on file ends.

Whitespace cleanup in test

---

Makefile.in

This fixes out of tree builds when using slibtool (https://dev.midipix.org/cross/slibtool).
```
rdlibtool: error logged in slbt_exec_compile(), line 158: path not found: src/hostapi/skeleton/.libs/.
make: *** [Makefile:227: src/hostapi/skeleton/pa_hostapi_skeleton.lo] Error 2
```
Full log:  [build.log](https://github.com/PortAudio/portaudio/files/5846439/build.log)

build: Add missing src directory.

---

.gitignore
configure
configure.in

Improve the way we generate the path to the SDK so that it
it not tied to specific versions.
Also changed macosx-version-min to 10.6
Fixes #378
Fixes #468

mac autoconf: support current and future SDKs

---

src/hostapi/wdmks/pa_win_wdmks.c

The fix for DEFINE_GUID that was recently added in pa_win_wdmks.c is also needed for the MSVC compiler.
Latest versions of the compiler support the `/Zc:preprocessor` option which is conforming to C99 and later standards
https://docs.microsoft.com/en-us/cpp/build/reference/zc-preprocessor?view=msvc-160
so it generates the exact same error as Clang (too many arguments error).

use variadic arguments in DEFINE_GUID also for MSVC

---

doc/src/tutorial/writing_a_callback.dox
include/pa_win_wasapi.h
ltmain.sh
src/hostapi/coreaudio/notes.txt
src/hostapi/coreaudio/pa_mac_core.c
src/hostapi/coreaudio/pa_mac_core_old.c
src/hostapi/dsound/pa_win_ds.c
src/hostapi/wasapi/pa_win_wasapi.c
src/hostapi/wdmks/pa_win_wdmks.c
src/hostapi/wmme/pa_win_wmme.c
src/os/unix/pa_unix_util.c
test/patest_write_stop_hang_illegal.c

Found via `codespell v2.1.dev0`  
`codespell -q 3 -L chello,gord,guid,numer,pres,uint,wirth`

Fix user-facing and non-user-facing typos 

---

src/hostapi/coreaudio/pa_mac_core.c

pa_mac_core.c: add missing definition to fix build on older systems

---

src/hostapi/alsa/pa_linux_alsa.c

Clean up whitespace in src/hostapi/alsa in preparation for .editorconfig.

---

configure
configure.in

Previously, only portaudio.h was installed when building under mingw using
make. This behavior differs from CMakeLists.txt PA_PUBLIC_INCLUDES where
pa_win_*.h header files are installed.
To cross-compile using MXE (https://mxe.cc/) we need pa_win_*.h headers.
Add them to configure.in so that they are installed.
Patch by Stefan Hajnoczi
Fixes #311

configure: add INCLUDES for mingw build

---

configure
configure.in

Add additional architecture to builds.
Fixes #445

configure: add arm64 for Mac M1

---

src/hostapi/oss/pa_unix_oss.c

It may not be provided by all OSS implementations, so wrap the cases in
`#ifdef AFMT_S32_NE`.

OSS: support 32-bit signed format AFMT_S32_NE

---

Makefile.in

When building portaudio with `-j2` or greater, slibtool (https://dev.midipix.org/cross/slibtool) and `ccache(1)` the build fails because `mkdir(1)` is slower than slibtool. This does not seem to happen with GNU libtool which is slower than `mkdir`.
```
rdlibtool: error logged in slbt_exec_compile(), line 158: path not found: src/common/.libs/.
make: *** [Makefile:228: src/common/pa_allocation.lo] Error 2
make: *** Waiting for unfinished jobs....
touch lib-stamp
```
Full log: [build.log](https://github.com/PortAudio/portaudio/files/5847183/build.log)
I fixed this by applying the `lib-stamp` as a dependency wherever it might be needed to be sure this doesn't happen again.

build: Fix builds with parallel make.

---

build/msvc/portaudio.def
cmake_support/template_portaudio.def
include/pa_win_wasapi.h
src/hostapi/wasapi/pa_win_wasapi.c

The IMMDevice pointer enables access to audio device capabiltiies not exposed by PortAudio.
https://docs.microsoft.com/en-us/windows/win32/api/mmdeviceapi/nn-mmdeviceapi-immdevice

wasapi: add PaWasapi_GetIMMDevice function

---

src/hostapi/coreaudio/pa_mac_core.c

Change version logic to allow for major 11 or later.
Partial fix for #492

macos: consider major version 11

---

Makefile.in

(i will create a separate pull request later that exports PaWinMME_* symbols and ammend the portaudio.defs)

configure/make: export PaWasapi_* and PaWasapiWinrt_* symbols

---

src/hostapi/dsound/pa_win_ds.c

Removes a doubled endline at the end.

Cleanup whitespaces in DSound

---

src/hostapi/oss/pa_unix_oss.c

Removes a doubled endline at the end.

Cleanup whitespaces in OSS

---

src/hostapi/wasapi/pa_win_wasapi.c

Fixed glitchy audio in case of Exclusive mode, Polling mode, 24-bit packed format and USB DAC as output device. Other audio devices using the same combination could be affected too.
The reason of glitches is periodic underrun which can only be fixed by using paUtilFixedHostBufferSize mode which is trying to fill the available host buffer more rapidly. As a bonus paUtilFixedHostBufferSize results in less CPU usage as it will consume the whole user buffer per pass.

wasapi: Fixed glitchy audio in case of Exclusive mode and 24-bit packed format.

---

src/hostapi/wasapi/pa_win_wasapi.c

Fix WASAPI compilation on VS2010
- use C89 syntax for variable declaration
- use "_inline" keyword instead of "inline" when compiling with VS2010 and earlier

wasapi: Fix compilation for VS2010.

---

src/hostapi/wasapi/pa_win_wasapi.c

With this PR all files in src (minus iasiothiscallresolver and mingw-include) have clean whitespaces according to the recently added editorconfig

WASAPI final whitespace fix

---

configure
configure.in

Use AC_COMPILE_IFELSE because AC_TRY_COMPILE is deprecated.
Include cdefs.h because it has checks for architcture.
Fixes #505

configure: better test for Mac OS arch

---

src/hostapi/jack/pa_jack.c

This fixes various bugs in the JACK host API exposed by PipeWire. Refer to the commit messages for details. I think this should be included in the upcoming 19.7 release because Linux distros are about to switch to PipeWire by default in the next few months (Fedora 34 and Ubuntu 21.04 at least).
I usually write C++ and don't have much experience with C so please point out if I'm doing something wrong. The `replace_string` function might not be the most efficient, but it works, and this is not performance critical code or we wouldn't be using regexes here already.

JACK PipeWire fixes (escape regex chars)

---

test/patest_converters.c

They were reversed.
Also added void casts to prevent unused parameter warnings.
Fixes #541

fix patest_converters.c argc argv order

---

test/patest_unplug.c

To prevent compiler errors and to avoid controversy over
stdint.h vs inttypes.h.
Fixes #550

patest_unplug.c: change int32_t to int

---

qa/paqa_devs.c

before including math.h
Fixes #551

paqa_devs.c: define _USE_MATH_DEFINES

---

bindings/cpp/INSTALL
configure
configure.in
doc/src/tutorial/compile_mac_coreaudio.dox
src/hostapi/coreaudio/pa_mac_core.c

This is the final PR for item #218
It removes support for OS X 10.5 Leopard and removes deprecated calls to `Gestalt`
It also updates the documentation to reflect the changes.

[macOS] drop support for 10.5

---

src/hostapi/wasapi/pa_win_wasapi.c

Fixed compilation with MinGW (W64) when targeting 32-bit platform by trying to detect presence of BYTE_BLOB presence with _BLOB_DEFINED define which is defined by MinGW (W64).
Fixes #354 issue.

wasapi: Fixed compilation with MinGW (W64)

---

src/hostapi/wmme/pa_win_wmme.c

fixes https://bugzilla.audacityteam.org/show_bug.cgi?id=1969
Another old patch from Audacity

MME: fix comparison of pointers

---

src/hostapi/alsa/pa_linux_alsa.c

Avoid compiler warning suggesting the buffer is too small:
../PortAudioLib/portaudio/src/hostapi/alsa/pa_linux_alsa.c: In function 'BuildDeviceList.constprop':
../PortAudioLib/portaudio/src/hostapi/alsa/pa_linux_alsa.c:1304:45: warning: '%s' directive output may be truncated writing up to 49 bytes into a region of size between 46 and 50 [-Wformat-truncation=]
snprintf( buf, sizeof (buf), "%s%s,%d", hwPrefix, alsaCardName, devIdx );
^~                ~~~~~~~~~~~~
../PortAudioLib/portaudio/src/hostapi/alsa/pa_linux_alsa.c:1304:42: note: directive argument in the range [0, 2147483647]
snprintf( buf, sizeof (buf), "%s%s,%d", hwPrefix, alsaCardName, devIdx );
^~~~~~~~~
../PortAudioLib/portaudio/src/hostapi/alsa/pa_linux_alsa.c:1304:13: note: 'snprintf' output between 3 and 65 bytes into a …

alsa: Increase snprintf buffer size to fix warning

---

build/msvc/portaudio.def
cmake_support/template_portaudio.def

FIXED: `build/msvc/portaudio.def` was missing Pa_GetVersionInfo so given function was not exported to the resulting DLL

- added Pa_GetVersionInfo to portaudio.def

---

include/portaudio.h

Add documentation indicating that Pa_ReadStream, Pa_WriteStream, Pa_GetStreamReadAvailable and Pa_GetStreamWriteAvailable are only valid while the stream is running (between calls to Pa_StartStream and Pa_StopStream.)
Resolves #579

Improve blocking read/write API docs.

---

src/hostapi/alsa/pa_linux_alsa.c

ALSA added nanosecond timestamps in library version 0.9.1.  Use these
instead of microsecond timestamps for reporting audio timestamps as well
as underrun/overrun times.
alsa-lib version 0.9.1 was released on Mar 11 2003.  I had fallback code
to use non-hires timestamps, but after 18 years it didn't seem
necessary, and I removed it from this commit.

Alsa: Use hires timestamps

---

src/hostapi/coreaudio/pa_mac_core.c

Prevent compiler warnings.
This is an alternative to #568.

pa_mac_core.c: init streamLatency and others

---

src/hostapi/alsa/pa_linux_alsa.c

Prevent compiler warnings.
Alternative to #567

alsa: init stream variable in pa_linux_alsa.c

---

CMakeLists.txt
src/hostapi/asio/pa_asio.cpp
src/hostapi/dsound/pa_win_ds.c
src/hostapi/wmme/pa_win_wmme.c
src/os/win/pa_win_coinitialize.c
src/os/win/pa_win_util.c
src/os/win/pa_win_util.h

This PR addresses items #176 and #392.
For #176:
It creates a new function `PaWinUtil_ConvertSystemError` which gets the text of a win32 error and passes it
to `PaUtil_SetLastHostErrorInfo`. It changes calls to all win hostapis to call the new function which greatly reduces code duplication.
For #392:
`PaWinUtil_ConvertSystemError` explicitly calls `FormatMessageW` and converts the message buffer.
Additional fixes:
1. `PaWinUtil_ConvertSystemError` does not allocate memory anymore. It uses a stack buffer of size 1024 which is the size of the buffer we use in `PaUtil_SetLastHostErrorInfo` (`PA_LAST_HOST_ERROR_TEXT_LENGTH_==1024`).
2. It adds the `FORMAT_MESSAGE_IGNORE_INSERTS` flag which maybe needed in some cases as explained by Raymond Chen here: …

PaWinUtil_SetLastSystemErrorInfo

---

src/os/unix/pa_unix_util.c

The currently used clock, CLOCK_REALTIME, will have discontinuous jumps, forward
and backward, when the system clock is adjusted.  This is bad for synchronizing
audio.  CLOCK_MONOTONIC does not have jumps, and never moves backward, but does
have the continuous adjustments done by NTP to increase clock accuracy.
Since kernel 2.6.25 ALSA has use CLOCK_MONOTONIC by default for timestamps
(commit b751eef1 from Dec 13 2007).  This change means the timestamps provided
in the PA callbacks can be compared to PaUtil_GetTime(), which currently does
not work.
The function used on MacOS, mach_absolute_time(), behaves like CLOCK_MONOTONIC.
If the system does not have CLOCK_MONOTONIC, fallback to CLOCK_REALTIME, which
is what alsa-lib does for such systems.  Which at this point would need to be
very …

Have PaUtil_GetTime() use monotonic time on Unix

---

src/hostapi/wmme/pa_win_wmme.c

This PR removes the last occurance of TCHAR from the portaudio code by explicitly using wchar_t.

replace LPCTSTR with LPCWSTR

---

src/common/pa_front.c
src/common/pa_util.h
src/hostapi/alsa/pa_linux_alsa.c
src/hostapi/asihpi/pa_linux_asihpi.c
src/hostapi/jack/pa_jack.c
src/hostapi/oss/pa_unix_oss.c
src/os/unix/pa_unix_util.h

This PR unifies all "stringizing" macros in the code by introducing a single PA_STRINGIZE macro in pa_util.h

PA_STRINGIZE

---

CMakeLists.txt
cmake/modules/FindOSS.cmake

This makes the root CMakeLists.txt simpler and more maintanable.

CMake: extract OSS finding code to a module

---

CMakeLists.txt
Makefile.in
build/msvc/portaudio.def
cmake/portaudio.def.in

This is a rebased version of #503.

export WMME host API specific extensions in DLL symbols

---

CMakeLists.txt
qa/loopback/CMakeLists.txt

Some IDEs like Qt Creator or Visual Studio use CMake model to construct
the project tree.
So for these IDEs, headers need to be included in targets.
As a side note, this is also what is done in CMake's own sources they add all headers (private and public ones) as sources.
This can add a small cost of maintaining CMakeLists.txt when adding new files: both `.h` and `.cpp/.c` files need to be added, not only `.cpp/.c` files.
I found that this incur a change in generated package for `macOS Clang framework PortAudio build` (probably a positive change):
Previously, `lib/portaudio.framework/Headers` was empty, with this commit this is a folder containing public headers.
In fact, `PUBLIC_HEADER` property requires that referenced headers are part of target_sources as stated here: …

CMake: include headers in sources of PortAudio

---

include/portaudio.h

For the function Pa_OpenDefaultStream, passing a value of 0 to numInputChannels
or numOutputChannels opens an output-only or input-only stream, respectively.

Fix documentation for Pa_OpenDefaultStream

---

src/hostapi/jack/pa_jack.c

This is required for building with MinGW.

JACK: add missing #include <pthread.h>

---

src/hostapi/jack/pa_jack.c

This breaks the build with MSVC.

JACK: remove unnecessary #include <unistd.h>

---

src/hostapi/jack/pa_jack.c

pthread_t is not guaranteed to be an arithmetic type by the POSIX
standard. In pthread4w it is implemented as a struct, so ==
does not work to compare two pthread_t values.

JACK: use POSIX pthread_equal instead of == to compare pthread_t

---

.github/workflows/cmake.yml

This allows contributors to test builds on GitHub Actions on their
own repositories without needing to open a pull request first.

GH Actions: run CMake build on all branches

---

doc/src/tutorial/compile_windows.dox
doc/src/tutorial/compile_windows_asio_msvc.dox

Update windows build docs to reflect the fact that MSVC build files have moved from `build\msvc` to `msvc`.
Fixes docs after #649

Update build docs for move of /build/msvc to /msvc

---

CMakeLists.txt

It seems that this was refactored recently, leading to nothing being added to PortAudioTargets.cmake, thus causing apps importing PortAudio that way not being able to find the PA includes.

Fix include directories missing in PortAudioTargets.cmake

---

CMakeLists.txt
src/common/pa_memorybarrier.h

OSMemoryBarrier() is deprecated and causes build failures
when "-Wall -Werror" are used.
Use -DPA_MAC_USE_OS_MEMORY_BARRIER if you want to use the old code
on APPLE.
Fixes #639

mac: use atomic_thread_fence() to avoid deprecation

---

src/hostapi/dsound/pa_win_ds.c

The warning is thrown as follows:
```c
[  5%] Building C object CMakeFiles/PortAudio.dir/src/hostapi/dsound/pa_win_ds.c.obj
pa_win_ds.c:54: warning: "_WIN32_WINNT" redefined
54 | #define _WIN32_WINNT 0x0400 /* required to get waitable timer APIs */
|
<command-line>: note: this is the location of the previous definition
```
`_WIN32_WINNT` is defined by GCC/MinGW and therefore it has to be checked before defining to 0x0400. If `_WIN32_WINNT` is defined to a lower value it will be redefined to 0x0400, therefore the expected behavior is preserved.
Closes #549

dsound: Fix warning of redefining _WIN32_WINNT when compiling with GCC/MinGW

---

cmake/PortAudioConfig.cmake.in

The problem being, that e.g. if(@PA_USE_ALSA@) expands to if() which is not valid CMake code

cmake: fix invalid config file being generated in some cases

---

src/hostapi/alsa/pa_linux_alsa.c

If an audio stream is only opened for capture in half-duplex
mode, then the self->playback.canMmap variable is false by
default. This triggers setup of a hostBufferSizeMode of
paUtilBoundedHostBufferSize, something that is only meant to
happen for playback streams under some conditions. This leads
to very distorted captured sound.
Fix this by also checking for self->playback.pcm, ie. that
the playback component is actually used, so this setting
only gets applied for half-duplex playback or full-duplex
playback + capture streams if needed.
Tested to work correctly now for playback, capture, and
full-duplex playback + capture.
Signed-off-by: Mario Kleiner <mario.kleiner.de@gmail.com>

alsa: Fix distorted sound from half-duplex capture.

---

cmake/portaudio.def.in
include/pa_win_wasapi.h
msvc/portaudio.def
src/hostapi/wasapi/pa_win_wasapi.c

Re implements this patch: https://github.com/audacity/audacity/commit/be7467c0e32c397d6223f2dc844a585d079b9875#diff-6ea9c8ba5ecef609fc4cfa9fbbb1bc11ad66acb997565df06ad6ce1562a10144 to add loopback for WASAPI devices.
I'm very new to C so I welcome any feedback or improvements to this PR.
Closes this:
PortAudio/portaudio#668
And would really help python-sounddevice users:
spatialaudio/portaudio-binaries#6
spatialaudio/python-sounddevice#287
https://github.com/tlecomte/friture/issues/64
https://github.com/spatialaudio/python-sounddevice/issues/281
spatialaudio/python-sounddevice#14 
Also see this project which maintains a fork of portaudio with loopback support specifically for PyAudio: https://github.com/intxcc/pyaudio_portaudio

Add WASAPI loopback implementation

---

doc/src/tutorial/compile_windows.dox
doc/src/tutorial/compile_windows_mingw-w64.dox
doc/src/tutorial/compile_windows_mingw.dox
doc/src/tutorial/tutorial_start.dox

issue #426 
Thanks to Ross for directions to the doc files. I am just cruising by with no expertise on cmake, portaudio, mingw-w64, or Windows audio APIs. All of these are directly relevant to these proposed changes, so if a preference looks strange, know that it is not likely a preference I hold strongly.
I did not build the doxygen docs. I hope the links work, because there is a "-" inside the link "compile_windows_mingw-w64" and I am not sure if doxygen allows "-" in links.
Comparing to https://github.com/PortAudio/portaudio/wiki/Notes_about_building_PortAudio_with_MinGW: ASIO information is omitted because I don't know anything about ASIO. The other APIs build, but I have not tested using them.
I added a warning to mingw's documentation page because it appears to be a zombie project, …

Add documentation for MinGW-w64

---

.github/workflows/cmake.yml

This fixes the HTTP 404 errors from vcpkg trying to download an old version of winpthread.

GH Actions: update vcpkg

---

src/hostapi/wdmks/pa_win_wdmks.c

Move declaration+definition of variable `nameIndex` to innermost scope. Removes redundant duplicate declaration. Remove unused variable `nameIndexHash`. Fixes #650

WDM/KS: Fix multiple declaration of `nameIndex`

---

aclocal.m4
configure
configure.in

This uses a macro from the Autoconf archive to check compiler features.
Fixes #674

autoconf: use c11 on Mac if supported

---

examples/paex_ocean_shore.c
examples/paex_record_file.c
src/common/pa_allocation.c
src/common/pa_allocation.h
src/common/pa_front.c
src/common/pa_process.c
src/common/pa_trace.c
src/common/pa_util.h
src/hostapi/alsa/pa_linux_alsa.c
src/hostapi/asihpi/pa_linux_asihpi.c
src/hostapi/asio/pa_asio.cpp
src/hostapi/audioio/pa_unix_audioio.c
src/hostapi/coreaudio/pa_mac_core.c
src/hostapi/dsound/pa_win_ds.c
src/hostapi/jack/pa_jack.c
src/hostapi/oss/pa_unix_oss.c
src/hostapi/skeleton/pa_hostapi_skeleton.c
src/hostapi/wasapi/pa_win_wasapi.c
src/hostapi/wdmks/pa_win_wdmks.c
src/hostapi/wmme/pa_win_wmme.c
src/os/unix/pa_unix_util.c
src/os/win/pa_win_util.c
src/os/win/pa_win_wdmks_utils.c

Make internal memory allocation utility functions allocate zero-initialized memory, and make this a documented guarantee. (Previously these allocations were not zero-initialized on Unix, but were zero-initialized on Windows). Rename `PaUtil_AllocateMemory` to `PaUtil_AllocateZeroInitializedMemory`. Rename `PaUtil_GroupAllocateMemory` to `PaUtil_GroupAllocateZeroInitializedMemory`. Remove redundant zero-initialization from dependent code. 
Note that it is possible that there are now allocations where zero-initialization is inappropriate for performance reasons. I intend to review the code for this as a separate issue.
Please consider rebase-and-merge (not squashing) to retain separation of critical changes to independent commits.
Fixes 396.

Make internal memory allocation utility functions allocate zero-initialized memory

---

src/hostapi/alsa/pa_linux_alsa.c

Return an error if outside reasonable range.
Fixes #594

alsa: remove asserts based on maxChans

---

src/common/pa_front.c

Increase max supported sample rate to 768000 Hz to address existence of the capable hardware such as USB DACs and DAPs. 
Closes #737

Increase max supported sample rate to 768000 Hz to address existence of the capable hardware

---

msvc/portaudio.dsp

(/Gm option was not present for any other target).
Fixes #730.

msvc/portaudio.dsp: remove /Gm option from MSVC Win32 Debug builds 

---

qa/loopback/src/paqa.c

This modernizes paloopback code around TestParameters handling by merging PaQa_SetDefaultTestParameters() and PaQa_OverrideTestParameters(), and using proper scoping instead of error-prone "change this param and then restore it later" patterns.
As a nice side effect, this also fixes a bug where user options would be ignored during the "Test Sample Formats using Half Duplex IO" phase because a PaQa_SetDefaultTestParameters() call was made without being followed by PaQa_OverrideTestParameters(), hence demonstrating why it's a good idea to merge these two functions.

Improve paloopback test params handling

---

qa/loopback/src/paqa.c

This fixes a regression introduced in 5b5feb3 where, during sample rate testing, the test duration would be computed based on the global sample rate instead of the chosen sample rate, resulting in the test running for too long or not long enough depending on the sample rate being tested. The main symptom is that paloopback would complain about timeouts when testing sample rates 8000, 11000 and 16000.

paloopback: fix wrong test duration

---

src/hostapi/wasapi/pa_win_wasapi.c

1) Refactored audio client instance creation by joining separate versions for input/output.
2) Removed unused code related to `IAudioEndpointVolume`.
3) Left comment about double buffering on PA WASAPI side inside `_CalculateFramesPerHostBuffer`.
Change 1. makes implementation more compact.
Change 2. removed `IAudioEndpointVolume` related code which was always unused by PA implementation.
Change 3. does not change PA WASAPI behavior, it just adds the comment about enforced double buffering.

wasapi: Refactored audio client instance creation.

---

src/hostapi/wdmks/pa_win_wdmks.c

This fixes an issue where Pa_OpenStream() would fail on WDM-KS WaveRT devices if suggestedLatency is zero.
Fixes #761

WDM-KS: don't request a zero buffer size

---

examples/paex_read_write_wire.c
qa/loopback/src/paqa.c
qa/paqa_devs.c
src/hostapi/jack/pa_jack.c
test/patest_dsound_find_best_latency_params.c
test/patest_leftright.c
test/patest_wmme_find_best_latency_params.c

This PR is a spin-off of #780 that focuses on fixing a number of trivial low-hanging fruit warnings.
Note that this PR only fixes a few classes of warnings, not all of them. It's a step in the right direction, though.

Fix some low-hanging C warnings

---

configure
configure.in

Warnings should not be turned into errors by default as that can cause difficulties for people who just want to build PortAudio, not work on it. Also this is inconsistent with other platforms.
This PR is a spin-off of #780.

Remove -Werror from autotools darwin build

---

.github/workflows/compare_def_files.yml
pa_compare_def_files.py

This CI action should ensure that our `.def` files will not diverge in future (see e.g. #323). It compares the symbols and ordinals listed in each `.def` file, and reports an error if there are missing symbols or if an ordinal does not map to the same symbol in both files.
As an alternative to this CI action, I considered merging the `.def` files. However, `cmake/portaudio.def.in` is not a real `.def` def file, but an input file that is converted to a `.def` file by CMake's `configure_file` function. It seems unlikely that we can easily replace this `.def.in` file with a raw `.def` file without significant complexity.
Fixes #785

Add CI action that compares msvc and cmake .def files 

---

CMakeLists.txt

Its not recommended to use a global settings in an cmake library, because this variable forces (when portaudio is used as an insource dependency)  to build every library as an shared or static variabe, which is not preffered (at least thats my guess, because it limits the usage from the library) In my proposal this can be easily fixed, because an local varirable instead of an globalone is used.)

Remove usage of global BUILD_SHARED_LIBS variable

---

src/hostapi/wdmks/pa_win_wdmks.c

In my tests with latency < 40 ms on Win10 with embeded Realtek sound card, WDM KS capture resulted in sound with lots of cracks. 
I digged into the code and found out 1) there is a wrong assumption that host buffer position should be either 0 or 1/2 of buffer size when event is handled, 2) ensured that host ring buffer is read both from the end and the beginning if necessary (the exisiting code might resulted in reading non-initialized data beyond the end of the host buffer)

Fix for WDM KS WaveRT low-latency microphone capture quality

---

include/portaudio.h
src/common/pa_front.c

This fixes a stack overflow when a diver uses portaudio as well like FlexAsio
Fixes: https://github.com/PortAudio/portaudio/issues/766

Pa_Initialize(): Guard against recursive calls.

---

src/common/pa_util.h

try to stop #795 happening again

docs: warn against using PaUtil_GetTime when a specific clock is required.

---

.github/workflows/cmake.yml
CMakeLists.txt

This pull request adds a new CMake option that makes it easy and convenient for PortAudio developers to turn warnings into errors, making it easier to find problems while iterating on code.
The option is then enabled on CI, ensuring that any future PortAudio changes are warning-free.
The option is not enabled by default because that would run the risk of breaking the build for people who don't have the same build setup as the CI (in particular, compiler type and version), and might trigger different warnings as a result. In particular, we don't want to break people who are merely interested in building PortAudio, but not interested in making changes to PortAudio.
Unfortunately the current code is not free of warnings. We should clean up the codebase to remove all warnings, but that will …

Treat warnings as errors on CI

---

CMakeLists.txt

These warnings are not currently being triggered. Their presence is probably the result of merge confusion between #780 and #799.

Remove some warnings from allowlist

---

CMakeLists.txt
qa/loopback/src/paqa.c

Fixes:
> wd4146: W2 unary minus operator applied to unsigned type, result still unsigned
See next comment for details.

Fix MSVC warning wd4146 unary minus operator applied to unsigned type

---

bindings/cpp/CMakeLists.txt

I suggest to add this quick fix that adds also `RelWithDebInfo` to the configurations allowed to install portaudiocpp.pc, otherwise you won't have support for pkg-config when building a release package with separate debugging information.
Actually, besides that, `RelWithDebInfo` is identical to Release.

bindings/cpp: CMake: support pkgconfig with RelWithDebInfo

---

src/hostapi/wmme/pa_win_wmme.c

Currently, the MME Host API code only creates 16-bit integer MME buffers. All audio data provided by the user is therefore converted by PortAudio to and from 16-bit, regardless of the user buffer format.
This basically makes it impossible to pass 24-bit audio through the MME Host API.
If the user buffer format is not 16-bit, this also causes pointless conversions to take place, *even if the hardware is running at 16-bit*, because modern Windows versions (Vista+) convert the data to floating point behind the scenes before it is handed off to the hardware. This can lead to silly situations where 32-bit float samples from the user are (lossily) converted to 16-bit by PortAudio, then ended off to Windows via MME, only to be converted back to 32-bit float again, before finally being converted …

mme: don't restrict the host buffer to 16-bit

---

CMakeLists.txt

This fixes https://github.com/PortAudio/portaudio/issues/828
From CMake 3.24 we can use a special generator expression for frameworks. 
But since PortAudio is on 3.1.0 I did changed it to the -Wl syntax explicit.

Don't use apsolute path when linking to macOS frameworks

---

src/common/pa_converters.c

This is code guarded by PA_USE_C99_LRINTF. Fixes #390.

Remove all alternative sample conversion code using lrintf in pa_converters.c

---

configure.in

As Jack and Pulseaudio both needs Ringbuffer that include can be done in same place. In configure.in also Pulseaudio header file was included before it was sure that it was really needed.
Commit makes sure that Pulseaudio include is available only if it's needed as it can cause failing in build if Pulseaudio develoment files are not available.

pulseaudio: Move Pulseaudio include in correct place when using autoconf

---

src/hostapi/pulseaudio/pa_linux_pulseaudio.c

The call to PaPulseAudio_UnLock( pulseaudioHostApi->mainloop ) in error-label is performed on 'pulseaudioHostApi' after 'pulseaudioHostApi' has been freed by PaPulseAudio_Free

Fix 'pulseaudioHostApi' use-after-free in PaPulseAudio_Initialize

---

src/hostapi/wdmks/pa_win_wdmks.c

Match the behavior of guiddef.h in both mingw and the Windows SDK headers. This prevents linking errors caused by multiply defined symbols when linking against certain Windows SDK libs (like dxguid.lib).

wdmks: declare GUIDs with selectany attribute

---

src/hostapi/pulseaudio/pa_linux_pulseaudio.c
src/hostapi/pulseaudio/pa_linux_pulseaudio_cb.c
src/hostapi/pulseaudio/pa_linux_pulseaudio_internal.h

This will translate the client provided suggestedLatency in seconds into microseconds and pass them to Pulseaudio, so the client has some control over required latency.
Invalid values < 1 microseconds get mapped to the default minimum latency, currently 10 msecs.
This replaces the previous hard-coded latency of ~2 msecs, which turned out to be too low on some tested mid-range systems and caused audio buffer underruns and audio artifacts.

pulseaudio: Make use of suggestedLatency stream parameter.

---

src/hostapi/wasapi/pa_win_wasapi.c

ADC capture time must be earlier than currentTime, as the capture time of any received samples in a buffer must be in the past.
Fix the wrong sign in calculation to fix this.

wasapi: Fix wrong sign in timeInfo.inputBufferAdcTime calculation.

---

.github/workflows/cmake.yml

As Pulseaudio is not currently build on Github workflow build. PR Adds it at least for CMake build

workflows: Add Pulseaudio to Github workflow build

---

src/hostapi/pulseaudio/pa_linux_pulseaudio.c

When PaPulseAudio_Initialize fails it does not currently do it very well as bug report  #848 tells. Now Only free lock if it's initialized enough to be unlocked.
Unlocking is done after allocations are done. That is because Locking is just after allocations and next `goto error` should have allocated memory and drop to that. Also now Group freeing code is one place.
Resolves #848

pulseaudio: fix PaPulseAudio_Initialize unlocking

---

src/hostapi/dsound/pa_win_ds.c

Currently, the DirectSound Host API code only creates 16-bit integer DirectSound buffers. All audio data provided by the user is therefore converted by PortAudio to and from 16-bit, regardless of the user buffer format.
This basically makes it impossible to pass 24-bit audio through the DirectSound Host API.
If the user buffer format is not 16-bit, this also causes pointless conversions to take place, *even if the hardware is running at 16-bit*, because modern Windows versions (Vista+) convert the data to floating point behind the scenes before it is handed off to the hardware. This can lead to silly situations where 32-bit float samples from the user are (lossily) converted to 16-bit by PortAudio, then ended off to Windows via DirectSound, only to be converted back to 32-bit float again, …

dsound: don't restrict the host buffer to 16-bit

---

cmake/modules/FindJACK.cmake

Silences CMake warning when MSVC is selected as generator:
```
CMake Warning at cmake/modules/FindJACK.cmake:43 (find_package):
By not providing "Findpthreads.cmake" in CMAKE_MODULE_PATH this project has
asked CMake to find a package configuration file provided by "pthreads",
but CMake did not find one.
Could not find a package configuration file provided by "pthreads" with any
of the following names:
pthreadsConfig.cmake
pthreads-config.cmake
Add the installation prefix of "pthreads" to CMAKE_PREFIX_PATH or set
"pthreads_DIR" to a directory containing one of the above files.  If
"pthreads" provides a separate development package or SDK, be sure it has
been installed.
Call Stack (most recent call first):
CMakeLists.txt:138 (find_package)
```

cmake: Silence configuration warning when MSVC is selected as generator.

---

pa_whitelint.py

Fixes the following warnings when running the whitespace checker CI script:
```
/home/runner/work/portaudio/portaudio/./pa_whitelint.py:192: SyntaxWarning: invalid escape sequence '\s'
leadingWhitespaceRe = re.compile(b"^\s*")
/home/runner/work/portaudio/portaudio/./pa_whitelint.py:221: SyntaxWarning: invalid escape sequence '\s'
trailingWhitespaceRe = re.compile(b"\s*$")
```

pa_whitelint.py: escape backslashes in regex strings (fixes warning in CI)

---

CMakeLists.txt
configure
configure.in
src/hostapi/jack/pa_jack.c
src/os/unix/pa_pthread_util.c
src/os/unix/pa_pthread_util.h
src/os/unix/pa_unix_util.c
src/os/unix/pa_unix_util.h

- Ensure that the clock that is configured on the cond object is the one that is used to compute the wait deadline
- Ensure that the most appropriate clock is selected on each platform based on availability `CLOCK_BOOTTIME` > `CLOCK_MONOTONIC` > `CLOCK_REALTIME` (on Mac use gettimeofday because other clock interfaces are either not available or broken).
Used directly or indirectly by pa_jack, pa_alsa, pa_asihpi
Resolves #795, #807.

centralize clock handling for pthread_cond_timedwait

---

src/hostapi/asio/pa_asio.cpp

Validation for PaAsioStreamInfo currently fails if the channelSelectors field is null.  As of March 1, 2024 channelSelectors is the only feature enabled by this structure but PR #519 will add another.
This PR amends the check so channelSelectors is only validated if the paAsioUseChannelSelectors flag is set in PaAsioStreamInfo.

Fix bug: Permit AsioStreamInfo without channel selectors

---

src/hostapi/pulseaudio/pa_linux_pulseaudio.c
src/hostapi/pulseaudio/pa_linux_pulseaudio_cb.c

Rework Pulseaudio stream starting and initialization code little bit more readable form. Commit also reworks stream starting to work more reliable.
PR reworks also error reporting as it should be first class citizen if there is better stream handling and initialization.
This should overcome problems from PR #857

pulseaudio: Rework some initialization code and have better error reporting

---

src/hostapi/pulseaudio/pa_linux_pulseaudio_cb.c

Fixing situation when Portaudio pulseaudio stream is created but never opened but just closed. application like Audacity does it like that with stream and that caused long delay before closing as stream could not be in correct state

pulseaudio: Make sure there is no delay in closing if stream is not open (#895)

---

doc/utils/checkfiledocs.py
test/patest_suggested_vs_streaminfo_latency.py

Print is a function in Python 3.  https://docs.python.org/3/whatsnew/3.0.html

Upgrade Python 2 code to Python 3

---

doc/utils/checkfiledocs.py

https://portingguide.readthedocs.io/en/latest/builtins.html#removed-file
https://docs.python.org/3/whatsnew/3.0.html#builtins
> Removed the `file` type. Use [`open()`](https://docs.python.org/3/library/functions.html#open). There are now several different kinds of streams that open can return in the [`io`](https://docs.python.org/3/library/io.html#module-io) module.

file() was removed in Python 3 in favor of open()

---

.github/workflows/cmake.yml

GitHub CI now defaults to arm64 Apple Silicon CI runners we believe
Hopefully fixes #907

CI: switch vcpkg_triplet to arm64-osx for compatibility with new default 

---

src/hostapi/jack/pa_jack.c

The latency calculation subtracts the size of one buffer from JACK's port latency value. I suspect this adjustment was made so that jackd's "asynchronous mode" appears to have the user's requested latency value even though jackd adds one extra buffer, thus increasing the real latency.
When jackd runs in "synchronous mode" or the more recent pipewire-jack implementation is used, PortAudio reports incorrect latency values of 0 seconds because the latency is exactly one buffer.
Fix the calculation to produce the real latency.

JACK: do not subtract buffer size from port latency

---

src/hostapi/wdmks/pa_win_wdmks.c

The previous code is only correct if `bytesPerFrame` is a power of two. If it's not (e.g. 2-channel 24-bit = 6 bytes per frame), then the computed buffer position is corrupted. This can lead the code to use the wrong buffer half, resulting in glitchy audio.
Fixes #763

Fix WDM-KS buffer position alignment

---

include/portaudio.h

update doc comments to document that API strings use UTF-8 encoding.

---

include/portaudio.h

Put `()` after function names for consistency. A few typos.

Generated documentation consistency

---

src/hostapi/wasapi/pa_win_wasapi.c

Workaround for the Realtek driver bug when driver mistakenly accepts Mono format with `IAudioClient_IsFormatSupported()` while subsequently fails in `IAudioClient_Initialize()`.
It is a long-lasting issue #875 which was resolved with a kind debugging help by @arkadijs.
Closes #875.

wasapi: Workaround for the Realtek driver "Mono" bug

---

examples/paex_record_file.c

`inputParameters.channelCount` and `outputParameters.channelCount` seems to have hardcoded 2 value, though the rest of the code seems to be using NUM_CHANNELS macro.

Use NUM_CHANNELS in example

---

.github/workflows/autotools.yml
test/patest_init.c

CI smoke test for autoconf make install/uninstall targets

---

src/hostapi/pulseaudio/pa_linux_pulseaudio.c
src/hostapi/pulseaudio/pa_linux_pulseaudio_cb.c
src/hostapi/pulseaudio/pa_linux_pulseaudio_internal.h

This PR unifies handling on pa_operation. It does not add or remove anything just adds function that should make easier not to get into infinite loop at the start.

Pulseaudio: Add function to handle Pulseaudio pa_operation

---

src/hostapi/dsound/pa_win_ds.c

This PR fixes a couple of issues with the way the DirectSound Host API cleans up its streaming thread, and also simplifies the code as a nice side effect.
Details can be found in the commit messages.

Fix issues with DirectSound thread cleanup code

---

CMakeLists.txt
examples/CMakeLists.txt
qa/loopback/CMakeLists.txt
test/test_use_cmake/CMakeLists.txt

Fixes #939 .
EDIT (added by RossBencina):
The purpose of this patch is to revert back to the CMake library name `portaudio` (all lowercase) that is used in our current V19.7 release. This avoids breaking things for all users of V19.7 CMake support. Note that this is not a `git revert` but rather a manual renaming.

Change CMake library name back to `portaudio` from `PortAudio`

---

CMakeLists.txt
cmake/modules/FindASIO.cmake
src/hostapi/asio/ASIO-README.txt

If download of ASIO api is complete, this performs the modification of "delete lpdrv" to "delete[] lpdrv".
Even in the case it was already done that would be harmless.

cmake: patch asiolist.cpp as issue #331 explains

---

qa/loopback/src/paqa.c
test/patest_wire.c

Now it uses the max channel count for the default devices.
For #595

Fix bad channel count in patest_wire.c

---

.github/workflows/cmake.yml

see: https://github.com/actions/toolkit/discussions/1890

fix broken CI: upgrade cmake CI to actions/cache@v4 because v2 is no longer available

---

test/patest_wire.c

explicitly require at least one input and one output channel.

patest_wire.c: improvement: validate channel counts

---

src/hostapi/dsound/pa_win_ds.c

see #782 for details and discussion.

dsound: clamp smaller buffer sizes to 62.5 ms on Vista and later (cherry-pick of #782)

---

CMakeLists.txt

CMake 4 refuses to accept a minimum required version below 3.5 without additional flags.

[cmake] Increase minimum required version of CMake to 3.5

---

src/common/pa_converters.c
src/hostapi/pulseaudio/pa_linux_pulseaudio.c
test/patest_ringmix.c

These are the commits from PR #1021 that have already been approved by Phil and I. I just updated the commit messages to be clearer.
I dropped the patch changing `sin` -> `sinf` since that is not C89. I will revert the other uses of sinf.

small fixups from PR #1021 with improved commit messages

---

src/common/pa_converters.c

Implements converters:
- Int32_To_UInt8_Dither
- Int24_To_UInt8_Dither
- Int16_To_UInt8_Dither
- Int16_To_Int8_Dither
Implementation is validated with `patest_converters`:
```c
== flags = paClipOff ==
=== Output contains non-zero data ===
Key: . - pass, X - fail
{{{
in|  out:      f32     i32     i24     i16      i8     ui8
f32             .       .       .       .       .       .
i32             .       .       X       .       .       .
i24             .       .       .       .       .       .
i16             .       .       .       .       .       .
i8             .       .       .       .       .       .
ui8             .       .       .       .       .       .
}}}
=== Combined dynamic range (src->dest->float32) ===
Key: Noise amplitude in dBfs, X - fail (either above failed or …
```

Implement 8-bit converters with Dither

---

src/hostapi/pulseaudio/pa_linux_pulseaudio_cb.c

Output copying what in incorrect place now that should be corrected. This is related: #965

pulseaudio: Correct output writing place where it's copied

---

src/hostapi/alsa/pa_linux_alsa.c
src/os/unix/pa_unix_util.h

Do not use the error macros that call "goto error" after an "error:" label.
Fixes #1037

Avoid infinite loops in ALSA code

---

test/patest_converters.c

The test computes maximum absolute differences over a non-exhaustive test signal. It does not really establish the dynamic range of the conversion. Update the labels on the printed output accordingly.

patest_converters.c: fix printed table label: "dynamic range" -> "max abs diff"

---

include/pa_mac_core.h
src/hostapi/coreaudio/pa_mac_core.c
src/hostapi/coreaudio/pa_mac_core_internal.h

Implements a function to retrieve the mac OS workgroup for a certain audio device.
I needed this myself in order to implement efficient multithreaded audio processing on Mac OS from Big Sur onwards.
See this for exlanation:
https://developer.apple.com/documentation/audiotoolbox/understanding-audio-workgroups

Add function PaMacCore_GetOSWorkgroup()

---

configure.in

On some platforms the `AX_CHECK_COMPILE_FLAG` macro (used in our `configure.in`) is not defined within the base `autotools` package, but rather in a separate `autotools-archive` package. If that package is not installed `AX_CHECK_COMPILE_FLAG` is not defined. This results in the use of `AX_CHECK_COMPILE_FLAG` being emitted verbatim into `./configure`, which in turn results in a cryptic error message:
```
./configure: line 19323: syntax error near unexpected token `-std=c11,'
./configure: line 19323: `        AX_CHECK_COMPILE_FLAG(-std=c11, CFLAGS="-std=c11 $CFLAGS", CFLAGS="-std=c99 $CFLAGS")'
Error: Process completed with exit code 2.
```
This patch improves the error diagnostic. The new diagnostic will be emitted at the time that `autoreconf` is run, and will not allow the `./configure` …

configure.in: cause a reasonable diagnostic if AX_CHECK_COMPILE_FLAG is not available

---

.github/workflows/autotools.yml
.github/workflows/cmake.yml

CMake CI is failing with the following error:
Seems to be failing on msys download:
`https://mirror.msys2.org/msys/x86_64/msys2-runtime-3.4.9-3-x86_64.pkg.tar.zst`
Latest is:
`https://mirror.msys2.org/msys/x86_64/msys2-runtime-3.4-3.4.10-5-x86_64.pkg.tar.zst`
See:
https://packages.msys2.org/packages/msys2-runtime-3.4?variant=x86_64
```
40s
Run cmake -G "Visual Studio [1](https://github.com/PortAudio/portaudio/actions/runs/17140627509/job/48627151449?pr=1061#step:6:1)7 2022" -DPA_USE_ASIO=ON -DASIO_SDK_ZIP_PATH="asiosdk.zip" -DCMAKE_TOOLCHAIN_FILE=D:\a\portaudio\portaudio/../vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_INSTALL_PREFIX=D:\a\portaudio\portaudio/../out -DCMAKE_BUILD_TYPE=RelWithDebInfo -DVCPKG_TARGET_TRIPLET=x64-windows -DPA_USE_SKELETON=ON -DPA_BUILD_TESTS=ON …
```

Fix CMake CI

---

src/hostapi/pulseaudio/pa_linux_pulseaudio.c
src/hostapi/pulseaudio/pa_linux_pulseaudio_cb.c

Problem
-------
A 262,144-byte leak is reported by ASAN when opening/closing a PulseAudio input stream. The leak originates from memory allocated in `PaPulseAudio_BlockingInitRingBuffer` and not freed on stream close or when `OpenStream` fails.
Root cause
----------
`PaPulseAudio_BlockingInitRingBuffer` allocates a raw buffer for the input ring. The buffer wasn’t freed in `PaPulseAudio_CloseStreamCb` or in the `openstream_error` cleanup path, leading to a persistent allocation per stream.
Fix
---
- In `PaPulseAudio_CloseStreamCb`, free `stream->inputRing.buffer` after stream termination and reset ring fields.
- In `OpenStream` error cleanup, free `stream->inputRing.buffer` if initialized and reset ring fields.
Impact and validation
---------------------
- Eliminates the ASAN-reported …

pulseaudio: free input ring buffer on close and open error (fixes #968)
